### ISSUE TITLE
ReservationExpired: Faktory job reservation expired

### ISSUE THREAD

**Issue by MarkMurphy** [jbielick/faktory_worker_node#163]
node.js version: 12.22.1

npm/yarn version: npm 6.14.12

faktory-server version: 1.4.0

`facktory-worker` package version: 4.1.4

Recently had a job take much longer than its allotted reservation time due to load on the server. This caused Faktory to re-enqueue that job while the original was still being worked without having been terminated. Unfortunately this particular job is difficult to make idempotent and so once a second instance started, bad things happened.

I'm looking into ways to work around this but I was curious if there's something I'm supposed to be doing in my job that I'm not, such as handling a SIGTERM for example.

How does the library respond to this event, if at all (I'm not sure if the client is notified by Faktory when this happens). If it doesn't, but could, I guess this is a feature request. Otherwise, any recommendations?

**Comment by jbielick** [comment]
> Recently had a job take much longer than its allotted reservation time due to load on the server.

If your job can take much longer, perhaps the reservation ought to be longer? I think that would be a safe bet. I don't think it will hold the reservation longer than the job actually takes so there shouldn't be a concern there. Just a thought.

> Unfortunately this particular job is difficult to make idempotent and so once a second instance started, bad things happened.

In these circumstances it can be helpful to use a distributed locking mechanism. That's usually a last resort, but it's also a practical solution. Check out redlock (node-redlock for node implementation) for more info.

>  I was curious if there's something I'm supposed to be doing in my job that I'm not, such as handling a SIGTERM for example.

The only thing you'll need to worry about is blocking the event loop. Blocking the event loop means nothing normally scheduled to occur can occur (like responding to signals and such).

> How does the library respond to this event, if at all (I'm not sure if the client is notified by Faktory when this happens). If it doesn't, but could, I guess this is a feature request. Otherwise, any recommendations?

What event are you referring to? If we're talking about a `SIGTERM` to the worker process (worker.work loop), we'll catch that SIGTERM and do a couple things:

1. Stop fetching jobs
2. Start draining the connection pool and wait `timeout` milliseconds for in-progress jobs to complete or fail (graceful exit)
3. Call `process.exit(1)` if we're still running after `timeout` milliseconds (ungraceful exit)

There's no extra userland code you need. Was your worker supposed to restart at some point during the job execution? That is, did you send the worker process a SIGTERM and it kept running? If the event loop were blocked by some bad code in a job, step 3 could not occur—there's nothing we could do about that because the event loop is blocked and the timeout code won't run until the event loop is unblocked.

**Comment by MarkMurphy** [comment]
Might help to have the full context. One job "ExtractFrames" spawns an ffmpeg command to convert a video into images of the individual frames. Another is enqueued for each image to perform some work on it. At some point the server CPU utilization reaches 100% and what would normally take under a minute to extract video frames took more than 30 minutes. (Obviously, some work to do around provisioning and autoscaling). Because of the slow down, this caused another instance of the ExtractFrames job to run in parallel and as you can imagine, things go downhill quickly from there.

Thanks for the tip on node-redlock, I was looking for something like that yesterday actually. That was one of the options I was considering.

**Comment by jbielick** [comment]
If you're asking about how a worker is notified that it exceeded the reservation timeout, there's no notification or implementation there. 

> Jobs are not notified they went over the time limit. The job will just be executed again. I think Faktory logs something but don't recall the specifics. Suggestions for improvement welcome. ... jobs aren't killed. they might finish. but they will be re-executed because they didn't finish within the timeout.

**Comment by MarkMurphy** [comment]
Ok, thanks. Sounds like making them idempotent is the only way to proceed in that regard.

**Comment by mperham** [comment]
With Faktory Enterprise you could use a special queue with a throttle of 1: https://github.com/contribsys/faktory/wiki/Ent-Throttling#types

**Comment by mperham** [comment]
I guess that would have a timeout too…
