### ISSUE TITLE
Default Acquire Timeout

### ISSUE THREAD

**Issue by vigandhi** [jbielick/faktory_worker_node#20]
Running the latest faktory version in brew (0.9.0-1) with the latest version of this library (2.2.0) seems to encounter a timeout when calling `faktory.work()` a multitude of times. This seems to be easy to trigger by calling `await faktory.work()` (with or without parameters) ~10 or more times on my machine (2016 quad core mbp). I've increased the timeout to 20s and that seems to resolve the problem.

https://github.com/jbielick/faktory_worker_node/blob/0934553b83189ab6f10239801df60d042290ee25/lib/connection-pool.js#L19

A few questions as I'm not entirely sure what's happening here:
1. Why is the default acquireTimeout 10s?
2. Should this be increased based on some factor of size (i.e. `10000 * size` also seems to work)?
3. Would it be simpler to allow the user of `faktory.work()` to input an acquireTimeout if they know this may be an issue?
4. Leaving out this timeout entirely will default it to infinite - what are the drawbacks?

I think some form of 2 would be the most seamless to the consumer.

**Comment by jbielick** [comment]
May I ask why you're calling `faktory.work()` in a loop? There's a `concurrency` option in this library for setting the number of concurrent workers per-process. The default concurrency is `20`, which means when you call `faktory.work()` _one time_, you create `20` connections to the faktory server. If you call `faktory.work()` 20 times, you create 400 connections, which is honestly too much juggling for node.js to do in a single process based on how this library works.

> Why is the default acquireTimeout 10s?

10s is an abundance of time for a client to connect. Connecting and handshaking to the faktory server takes milliseconds (and sometimes less). It should not need 10 seconds unless there's really bad network connectivity and even then, a longer timeout will probably not help.

> Should this be increased based on some factor of size (i.e. 10000 * size also seems to work)?

See top paragraph. I don't think you need to call `faktory.work()` twenty times. Calling it once with the default concurrency effectively creates 20 "workers".

> Leaving out this timeout entirely will default it to infinite - what are the drawbacks?

A timeout should _never_ default to infinity. 

Does this help? Please re-open if there's an issue with the concurrency setting or another alternative.

**Comment by jbielick** [comment]
If you're looking at the faktory server UI and you only see one worker, that's because this library lazily creates more workers based on the amount of work. It auto scales up and down based on activity from 1 to the max concurrency setting.

**Comment by vigandhi** [comment]
Thanks! This is helpful. We were using .work in a loop to create various
named queues independently. So for example all email related jobs go in the
queue named email, etc.

Sounds like we can work around this and thanks for the quick reply.

**Comment by jbielick** [comment]
Ah, if it's possible it would be best to start a group of processes independent of each other for each of those queues. There are some assumptions baked into this library that `work` is running by itself. For instance we listen to `SIGINT` to know when to gracefully shut down and I noticed when `work` is called multiple times there are multiple SIGINT handlers and things start going downhill.

If its helpful, here's an example of using node.js `cluster` module to fork the process multiple times and do something like what you're describing: https://github.com/jbielick/faktory_worker_node/blob/master/bin/faktory-cluster

In your situation it might look like:

```js
const cluster = require('cluster');
const faktory = require('faktory-worker');
const workers = {
  email: 10,
  default: 10,
};

if (cluster.isMaster) {
  Object.keys(workers).forEach(queue => {
    for (let i = workers[queue] - 1; i >= 0; i--) {
      const worker = cluster.fork();
      worker.send({ queues: [queue] });
    }
  });
  cluster.on('exit', (worker, code, signal) => {
    console.error(`worker ${worker.process.pid} died`);
  });
} else {
  process.on('message', ({ queues }) => {
    console.log('im working on %s', queues)
    faktory.work({ queues, concurrency: 10 });
  });
}
```

This script would fork as many times as you have workers in the `const workers` hash for each queue (key in the hash) and start 10 workers per fork. It doesn't do any process management (bringing it back to life after crashes and such) so I would recommend something like systemd in production but it should illustrate a forking model that would support that many workers.

Be warned that I got some weird behavior (had to restart faktory server a couple times) for this to work. Potentially node is hitting the server with too many connections and maybe something is getting stuck. When things go smoothly there are no timeouts.

**Comment by theoephraim** [comment]
Thanks for the info @jbielick!

We are going to try this and see if it works - however I'm not too keen on running a bunch of node processes rather than the recommended match your number of cores rule that I understand is the norm. The issue is that we have many different queues that are separated by type and each have their own level of concurrency. 

Is there anything that comes to mind why connections couldnt be shared in a setup like this?
Could a single connection handle all the communication for many queues with different concurrency levels?

**Comment by jbielick** [comment]
I don't think that level of specificity in your setup will be something that this library solves for you. In fact, it's already possible, right? I think you just need to spin up separate processes for your different worker pools:

process 1:
```
concurrency: 1, queues: ['accounting']
```

process 2
```
concurrency: 20, queues: ['stripe']
```

process 3
```
concurrency: 10, queues: ['shopify']
```

process 4
```
concurrency: 15, queues: ['amazon']
```

etc...

All the building blocks are there if I understand correctly—you'd just rather have this library handle how many workers are running per queue? I don't think that's something that this client should do—it just makes the code more complex for doing something that's already possible with simpler, smaller building blocks.

In my experience, the fewer queues you can have, the better off you'll be. I think this is generally what people strive for in sidekiq as well. If the only reason you need this functionality is because you want rate limiting, I'd say that's a misuse of the concurrency setting—it isn't intended for rate limiting and you could find a distributed great rate limiting library to help out here. Moreover, rate limiting in Sidekiq Enterprise is wonderfully implemented and it's likely that functionality will make its way to Faktory at some point. For the time being, I'd like to help you find a way to run these worker pools as you need to without adding a configuration that defines concurrency per-queue because I think that's a very narrow use-case.

**Comment by vigandhi** [comment]
What I’ve got going on a feature branch is child processes as described
originally. This seems to work fine as desired. I do however agree that
simplifying the queue structure may be beneficial in the long run
especially if rate limiting ends up making its way to faktory core.
