### ISSUE TITLE
How could I implement circuit breakers for workers?

### ISSUE THREAD

**Issue by ThisIsMissEm** [jbielick/faktory_worker_node#202]
I'm currently researching Faktory and usage in Node.js (after looking at other job queues), and I'm wondering how I'd go about implementing a means for a worker or set of workers to be temporarily paused. My use case is that I have to interact with a social media services' API, and that API can sometimes go down or exceed rate limits, in these cases, I think failing the job that encountered the limit would be okay, but then I'd like to instruct all workers of that particular job to actually stop working, until the coast is clear and the API is back up — there's no point in all jobs continuing to be started and continuing to fail when a circuit breaker has flipped.

Would this be implemented by having a side channel that subscribes to, say, a redis pub-sub notification that defines whether or not it's okay to call `Faktory.work` or call `worker.quiet()`? 

I can't find any information in the Faktory wiki about handling circuit-breakers for jobs either, but this can be vital to ensure distributed systems work reliably.

**Comment by jbielick** [comment]
An isolated queue with queue pausing is a pretty cool feature that could help here.

Aside from something built-in (which tends to be highly reliable based on Mike/ContribSys's reputation) you could implement something custom using the faktory_worker_node [middleware](https://github.com/jbielick/faktory_worker_node/blob/main/docs/api.md#faktoryusefn--faktorycontrol). The middleware is provided a faktory client and could be provided a redis connection as well. Something like:

1. add middleware that checks for a circuit **broken** in redis
2. if we're running job xyz and the circuit for xyz is broken, re-schedule the job using the faktory client and don't `await next()` (because that will execute the job)
3. if not broken or not job xyz, `await next()` and run the job

Something like that might allow you to rate limit at a high level. It would be difficult for me to abstract that in this library because this library does not have a distributed data store, node.js doesn't have `try/catch` for specific error types readily available (AFAIK), and this would be functionality pretty bespoke for the node client that would be lacking in other clients.

I hope this helps!
