### ISSUE TITLE
Queue order not respected

### ISSUE THREAD

**Issue by counterbeing** [jbielick/faktory_worker_node#22]
node.js version: node:8.12-alpine

npm/yarn version: yarn 1.10.1

faktory-server version: 0.9.0

facktory-worker package version: ^2.2.0

#### Code sample:

```js
    faktory.work({
      concurrency: 1,
      queues: ['node-scraper', 'node-crawler'],
      timeout: 25 * 1000
    })
```

#### Expected Behavior:

If the `node-scraper` queue is not empty a job should be processed from there, then once that is empty a job from `node-crawler` should be processed.

#### Actual Behavior:

A new job appears to be grabbed from the top of the stack. I just tested this by adding a new `node-crawler` job while there were 130 `node-scraper` jobs in queue. The next jobs to run were `node-crawler`.

#### Steps to reproduce the behavior or a test case:

Create a worker that listens to two queues. Queue A will be a short running process that generates many long running Queue B processes. The same worker listens to both queues. When long running processes in Queue B have accumulated, try adding another from Queue A, which should be executed only after all of Queue B have completed.

**Comment by jbielick** [comment]
Thanks for the detailed issue!

Hmm, I believe that's due to the queue shuffling:

https://github.com/jbielick/faktory_worker_node/blob/0907290dbd29fb7fb82818a1b245b2020d4a02b4/lib/worker.js#L120-L122

I think this should probably only occur when queues have weights, which is not implemented in this library. I think I jumped the gun on queue shuffling. It's been removed in v2.2.1 which is now on npm.

**Comment by counterbeing** [comment]
Thanks so much for your work on this super useful project! And for the quick turnaround! 👍 
I'll give it a go right now!

**Comment by counterbeing** [comment]
I just wanted to loop back and tell you that this is now working as expected!

**Comment by jbielick** [comment]
Excellent. I appreciate the feedback!
