### ISSUE TITLE
Can one client connection be used for the lifetime of an app?

### ISSUE THREAD

**Issue by CaryLandholt** [jbielick/faktory_worker_node#32]
Since as of version 3.0.0 per https://github.com/jbielick/faktory_worker_node/blob/master/CHANGELOG.md#300--2019-02-11, a connection pool is added to each client, is it advantageous/recommended to instantiate a single client connection to be used for the lifetime of an app?

Also, can you clarify what is meant by (taken from the changelog):
```Markdown
Client.connect() not necessary before using connection Client.connect() now connects and disconnects to test the connection details. A connection is created in the pool when it is needed.
```

**Comment by jbielick** [comment]
It may be helpful to define the terms a little bit:

**Connection**: a TCP socket connected to the faktory server. 
**Client**: an object that can be used to interact with the faktory server that implements the API of the faktory protocol (`push`, `fetch`, `fail`, etc). 

As of 3.0, your code can deal only with a `Client` object (one is returned from `faktory.connect()` or you can `new Client()` to get one). Prior to 3.0, your code still interacted with a `Client` object, but it held a single, stateful TCP socket that was used to send and receive data from the server. When this connection / socket got disconnected, the client was responsible for trying to reconnect and recover from failure behind the scenes. Your code could be (gleefully) oblivious to reconnections. 

I'm not a huge fan of handling connection retries and stateful sockets, so I would always recommend a creating a connection pool, as utilized and recommended in Sidekiq's docs and elsewhere, to maintain connectivity to a server over long-lived TCP connections. A single Client used concurrently (async) could also present some issues where packets are sent to the server and responses may not be received in the same order. I don't think this was an issue, but I thought it was worth engineering around.

So starting at 3.0, a `Client` starts a connection pool for you ("behind the scenes"). When you call one of the API methods like `push`, a Connection is checked out (or created if it isn't available) from the connection pool for the Client to use. This connection is held by the Client until the server responds. If you use the Client concurrently (almost definitely occurs for any app), each method call to the Client checks a connection out and back in. Connections are periodically reaped if they have become disconnected or if they have not been checked out for some time (stale).

Thus, connections become a little more expendable and much less precious as the pool scales up and down with usage. From a user perspective, you don't need to manage this pool or create it (for now).

Worker processes have and will continue to use a client pool since they concurrently use a Client and need high availability / resiliency.

The overall goal was to bake some resiliency into the code using this package by treating connections as brittle as they are and avoid writing reconnect logic with exponential backoffs and recovery scenarios.

Does that make sense?

**Comment by jbielick** [comment]
The description and language here may also be helpful: https://github.com/jbielick/faktory_worker_node/blob/master/docs/api.md#Client

**Comment by CaryLandholt** [comment]
Thanks @jbielick !
This was really helpful.

Let me play this back against my real use case.

I have an http handler that gets considerable traffic throughout the day - a few million requests.
The payload is then chunked up and pushed to faktory for further processing.

If I understand your response correctly, would you recommend the following?
```JavaScript
import faktory from 'faktory-worker'

const client = faktory.connect() // instantiate a faktory client for user during the life of the app

router.get('/some-path', async (req, res, next) => {
  // ...do some work

  await client.job('MY_JOB', [1, 2, 3]).push()
  await client.job('MY_JOB', [4, 5, 6]).push()
})
```

In the above example, I'm instantiating a single faktory client once and using it for the life of the app.
In addition, I'm not closing the client.

Does this make sense?  And I don't need to close the client manually?

**Comment by jbielick** [comment]
> Does this make sense? And I don't need to close the client manually?

Absolutely! And as for closing: I would try and do so, but it's not typically critical.

SIGINT or whatever signal you're sending typically terminates those connections, but it can be helpful to `await client.close()` to shut down the connection pool gracefully. I wouldn't worry too much about it unless you're having issues.

Also—you may have omitted some small details for brevity, so forgive me if these are already known. `faktory.connect()` is async, so you'll want to `await` that before starting your server. This ensures the connection is possible and ready before starting your app (helpful when it comes to health checks). I'd recommend adding the client to the request object in a middleware so it's available to all HTTP handlers instead of relying on the closure having access to the `client` var. It would look something like this:

```js
import faktory from 'faktory-worker';
import express from 'express';

const app = express();

router.get('/some-path', async (req, res, next) {
  // ... do some work
  await req.faktory.job(...).push();
  await req.faktory.job(...).push();
  next();
});

(async () => {
  const client = await faktory.connect();
  
  app.use(async (req, res, next) => {
    req.faktory = client;
    next();
  });  

  app.listen(...);
}).catch(console.error.bind(console));
```

But again, if you don't have any issues you're probably fine. Feel free to disregard.

**Comment by CaryLandholt** [comment]
Excellent! Yep, was going to use express middleware just like your code snippet. Thanks again!
