### ISSUE TITLE
Concurrency causing failure with connection limit 

### ISSUE THREAD

**Issue by emhagman** [jbielick/faktory_worker_node#37]
Regarding https://github.com/jbielick/faktory_worker_node/blob/1ae4482529fb70dc276be68d39ce10f2ea44cc31/lib/worker.js#L59

Is there a reason the `poolSize` for the client is set to `concurrency + 2`? We have concurrency set to 100 and have many queues open and this is causing Faktory to essentially grind to a halt to the point where using the Web UI does not work. We also use Elixir and the concurrency there is not a problem.

Unless each Redis connection is blocking while the job is running, this seems like overkill.

**Comment by jbielick** [comment]
Without a connection per "worker", I cannot guarantee workers won't queue waiting for a connection to use. IMO concurrency=100 is too high. I use a benchmark script often (`bin/bench`) to test out different configurations and concurrency north of 20 typically causes the event loop to get backed up. The benchmark script tests a job that is more or less an empty function. So I might ask how you decided on 100 workers per single CPU because that's a lot.

**Comment by jbielick** [comment]
Here's some crude benchmark data from my machine:

`bench/push` pushes 10K jobs.
`bench/work` consumes 10K jobs. Arg 2 is the concurrency.
`jobs/s` is the figure I'm paying attention to the most.

With:

```js
poolSize: this.concurrency + 2,
```

Concurrency=20

```
› bench/push && bench/work 20

processed: 10000
concurrency: 20
duration: 8.470984854s
jobs/s: 1181
```

Concurrency=100

```
› bench/push && bench/work 100

processed: 10000
concurrency: 100
duration: 7.878028564s
jobs/s: 1269
```

---

With:

```js
poolSize: Math.ceil(this.concurrency * 0.5),
```

Concurrency=20

```
› bench/push && bench/work 20 

processed: 10000
concurrency: 20
duration: 10.020042347s
jobs/s: 998
```

Concurrency=100

```
› bench/push && bench/work 100

processed: 10000
concurrency: 100
duration: 10.509228297s
jobs/s: 952
```

My goal was one connection per worker so there's no queueing. 100 concurrency is theoretically 5x more working throughput, but doesn't yield 5x throughput in reality even with a job that has no logic or I/O in it. We could certainly use a smaller pool size for concurrency of 100, but how does that scale back down for 20 workers? It just becomes complicated / arbitrary. Since I can't see 100 concurrency being optimal I don't recommend it and I could see how it would require a larger Faktory instance (more CPUs). So all in all this library is probably optimized for something like 20 concurrency because it's shown a good mix of tradeoffs and I don't think 20 tcp connections is a lot for a golang application.

Is it possible there's a mix of things at play that's causing the server slowdown? I don't really know what 100 concurrency means in elixir or how it does concurrency so I can't really compare it well.

**Comment by jbielick** [comment]
I'm totally new to reading Elixir, but it appears to me that the `faktory_worker_ex` library uses one process for fetching, and one process per worker. 

https://github.com/cjbottaro/faktory_worker_ex/blob/e632ee678e0ab8c0da0817d2417cf89f86cbda79/lib/faktory/supervisor.ex#L18-L25

Erlang VM threads are capable of using more than one CPU, so I imagine the throughput of the worker pool is much higher than a single-cpu-bound VM like v8 / nodejs. The architecture in this library is a bit different in that there's 1 process which starts _n_ coroutines (recurring events on the event loop) and each coroutine gets its own connection to `FETCH` and process jobs with. 

https://github.com/jbielick/faktory_worker_node/blob/1ae4482529fb70dc276be68d39ce10f2ea44cc31/lib/worker.js#L96-L101

From what I've heard, it's also common to need a connection to `push` a job within a job itself—in such cases it would be ideal to have a connection per-worker in order to not monopolize the connection pool by using it within jobs. Not necessarily a blocking operation like your above question, but not overkill either.

**Comment by emhagman** [comment]
@jbielick Thanks for looking into everything. Yes, we do in fact queue jobs within jobs but we already decrease the limit if we know we are on a worker itself, so I don't see that part as a big deal.

All of what you said makes sense. The Elixir library doesn't need 100 connections for a concurrency of 100 because of what you stated. This library separates what it calls`fetcher`s and `runner`s, defaulting the `fetcher`s to 1 as seen here https://github.com/cjbottaro/faktory_worker_ex/blob/0e9963b8e9ba63cd3b4937c3e677c804663517f9/lib/faktory/worker.ex#L62 which is only using 1 TCP connection and then can execute them in the `runner`s for `n` concurrency. I get it can do this because of the Erlang VM's abstraction and essentially the equivalent of goroutines which in Elixir are called a `Process` which can be spread across N cores.

Your design decision makes sense because I understand queueing locally increases complexity, but without it, we can't run many lightweight jobs in Node. I understand the throughput is less, but a difference of `317` jobs per second is not a big deal at all for us for our use case since sometimes we are waiting 10 seconds for a response back from some of these APIs. 

While I understand this may not be the standard use case, at a minimum, it would be nice to be able to tweak the configuration. We are fine with "slower" processing for higher concurrency since we are just waiting for responses back from an API that already takes much longer than the 3-second loss in time in your benchmarks. I'm more than happy to submit a PR if you'd like. If not, I can also just maintain a fork which is not a huge deal but not ideal.

We'll eventually move these jobs to Elixir anyways and then this will no longer be an issue but in the meantime, I'd appreciate any help 👍

**Comment by jbielick** [comment]
🤔 I wonder what the Elixir lib's `FETCH` throughput is if it only has one process serially `FETCH`ing.

I think I understand your use case a lot better now—thanks for the extra info. If we expose `poolSize` as a config option would that suffice?

**Comment by emhagman** [comment]
@jbielick That would work perfectly, thanks!

re: Elixir, I can see it being slow if it needed to process 1000s of jobs in a second, but that simply is not our use case, and if it were, we would simply up the number of `fetcher`s on the Elixir side (but not to equal the concurrency still).

**Comment by mperham** [comment]
Right, and the higher your latency to Faktory, the more fetchers you need
to saturate a worker.  In my experience, one fetcher will work fine for
normal loads where your latency is <= 5ms but if your jobs only take 5-25ms
(which is not normal), you'll want more than one fetcher.

**Comment by emhagman** [comment]
@mperham Thanks for chiming in. Makes sense to me 👍

**Comment by jbielick** [comment]
I thought I was copying the one fetch per processor concept from the sidekiq source, is that not how it works? Any other best practices in worker library design?

**Comment by mperham** [comment]
Sidekiq <4 used a single fetch thread which made it very sensitive to Redis
network latency.  Sidekiq 4+ uses $CONCURRENCY fetchers (each worker thread
fetches from Redis directly) to minimize latency. Sidekiq Pro's super_fetch
uses 2 threads for $REASONS.

**Comment by jbielick** [comment]
`poolSize` config option is now available in [`v3.2.0`](https://github.com/jbielick/faktory_worker_node/releases/tag/v3.2.0)

**Comment by jbielick** [comment]
@emhagman let me know if I can help further. One FYI: the pool is more or less a semaphore for FETCHing. Even if the poolSize is low, each worker will attempt to checkout a connection and FETCH. If the pool size is too low you'll probably see errors about timeouts while attempting to check out a resource from the pool.

https://github.com/jbielick/faktory_worker_node/blob/23c1b3df81cb60fa9ecbbe7fb87bf0380bbba398/lib/client.js#L59

This timeout is 5s by default. Not configurable today.

**Comment by emhagman** [comment]
Thanks @jbielick. Since the max time for `FETCH` when no job exists is 2 seconds, this should not be too much of an issue as long as I keep it around `concurrency * 0.5`. Appreciate the change!
