### ISSUE TITLE
npm or yarn?

### ISSUE THREAD

**Issue by MarkMurphy** [jbielick/faktory_worker_node#45]
Are we using npm or yarn as the package manager for this project? I'm also curious why the lockfiles are in the .gitignore? These are files that you should absolutely want to check in. Happy to open a PR for that.

**Comment by jbielick** [comment]
Use whichever you prefer. I think I prefer not having a lock file. If you notice something wrong, you could pin the development versions in package.json if you needed.

**Comment by MarkMurphy** [comment]
@jbielick  I think you're missing the point of what a lockfile is for and the issues it prevents. 

Without a lockfile npm installs dependencies into the node_modules directory non-deterministically. This means that based on the order dependencies are installed, the structure of a node_modules directory could be different from one person to another. These differences can cause “works on my machine” bugs that take a long time to hunt down.

Issues around versioning and non-determinism are solved by using lockfiles and an install algorithm that is deterministic and reliable. These lockfiles lock the installed dependencies to a specific version, and ensure that every install results in the exact same file structure in node_modules across all machines.

**Comment by jbielick** [comment]
@MarkMurphy If I'm being honest, your comment is a little condescending. Please assume I know what a lock file is for and that I've read the Yarn blog from which you copied that text. I'm familiar with the debate for ignoring/not ignoring the lockfile in libraries. I made a conscious decision _not_ to commit it.

That said, if you're having issues and adding it would help you, please let me know what issue you're experiencing and we can figure that out. If you're opposed on principle, let's leave it as-is for now. If you're planning on pull requesting a lock file, I would also ask that you 1.) update CI to use `npm ci` instead of `npm install` because otherwise the lock is useless, 2.) unpin dependencies (use optimistic matcher `^` for all packages), and 3.) plan to regularly update packages and commit changes to the lock file in this repo so we're not developing on old dependencies without realizing it.

**Comment by MarkMurphy** [comment]
My sincere apologies if I came across condescending. Not at all my intent and I’m glad you’re familiar with that post. I quite literally meant that I wasn’t sure if you were aware of the reasoning for the lock files because I didn’t get an explanation back as to why they’re ignored other than it being for personal preference. 

I’m personally not aware of any good reasons why we shouldn’t include a lock file so ultimately I guess I’m just looking for your insight on that and to be educated. 

Is it just so that contributors can choose whichever package manager they prefer?

**Comment by jbielick** [comment]
I think the argument (in favor of omitting the lock) I found most compelling was the "false sense of security" claim. 

First, I should state my assumptions:
- The package-lock is omitted from the package itself when published and it doesn't affect end-users at all. Thus, the lockfile would be exclusively for maintainers and CI.

The idea is this: you have dependencies you install, develop with, and lock via package-lock.json. You run tests, CI installs the same versions (you think), runs tests. Everything passes.

Advantages: 

- Deterministic installs in dev and CI and deterministic test suite dependencies resolution for posterity.
- All development on the project uses the same versions of dependencies.

Caveats:

- If you're not using `npm ci` in CI, you're not really getting locked versions of dependencies in CI. (I'd guess it wouldn't be deterministic resolutions either)
- This assumes you'll be updating your packages regularly, maybe even updating before every release to ensure new installations go well.

Disadvantages:

- As new package versions of your dependencies are published (matching your package.json requirements), new installations by end-users of this package will receive those upgraded dependencies, not the ones you were developing against. I don't look at / develop this package on even a weekly basis, so it can fall behind somewhat quickly. I _really_ dislike the surprise of a user install potentially getting a dependency version that won't even pass tests. I can't fully control this, but at least I know when CI runs on master before a publish that whatever a user would get for an install at that moment in time passes the tests (because CI simulates that). Does that mean local tests might pass and CI doesn't? Yes. That often indicates an actual issue—and I place a high value on surfacing those edge cases. 
- If someone opens an issue for a new incompatibility with a newer version of a dependency, I've found it difficult to upgrade _just that dependency_ in order to reproduce the issue. What's more likely is having a waterfall of dependency updates when you bump one (when you're a little bit behind on updates). At that point, you might encounter more than one incompatibility just trying to isolate a single test failure reproducing what someone is experiencing. Then you might be fixing several issues at once. That's a tough spot.
- If a dependency introduces an incompatibility, a user may not be able to find "the last working/compatible version" of that dep in our package lockfile.

An alternative: Not committing the package lockfile.

Advantages:

- New contributors install and get the latest versions and develop against those. They might encounter issues when developing. Those issues are part of the maintenance of the project and if a contributor doesn't have time for them, they probably shouldn't be contributing.
- CI is installing up-to-date dependencies during a build. Locking CI to "working" versions of dependencies is where that "false sense of security" comes to play for me. That's not what users are getting, so how much value is it providing? A snapshot in time of passing tests doesn't increase my confidence much when releasing a new version.

Disadvantages:

- You get a different version of dependencies (development, too) and a non-deterministic resolution of the dependency tree. It's structured chaos. I get that it could produce wildly inconsistent environments, but I would wager that it most often doesn't.

---

Like most things, both approaches have tradeoffs. I have come to prefer the latter. Does it scale? Probably not, but that's not a problem yet. I think I'm optimizing for "works when installed" instead of "tests always pass" if that makes sense. I'm amenable to adding a lockfile, but some of the nuance above would have to be solved via dependency update automation or something (dependabot?).
